name: Get MVP Odds 

on:
  workflow_dispatch:
  schedule:
    - cron: '30 15 * * *'

jobs:
  Get-NHL-MVP-Odds:
    name: Get Latest MVP Odds 
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3  
      
      - uses: r-lib/actions/setup-r@v2
        with: 
          use-public-rspm: true
          r-version: 'release'
          
      - name: Install libcurl and libssl on Linux
        run: sudo apt-get -y install libcurl4-openssl-dev
        shell: bash
        
      - name: Cache CRAN packages
        uses: actions/cache@v3 
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-r-${{ hashFiles('**/DESCRIPTION') }}
          restore-keys: ${{ runner.os }}-r-
          
      - name: Install CRAN packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with: 
          packages: jsonlite, dplyr
          
      - name: Run R update script
        run: Rscript nhl-mvp-odds.r
        shell: bash

      - name: Commit changes in data folder
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add data/mvp_odds*.csv
          git diff --cached --quiet || git commit -m "Auto-update: mvp odds"
        shell: bash

      - name: Push changes
        run: git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}