name: Publish Quarto Dashboard

on:
  workflow_dispatch:
  schedule:
    - cron: "0 13 * * *"  # 5/6am Pacific tume

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          extra-repositories: |
            https://timelyportfolio.r-universe.dev

      - name: Install system libraries
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev

      - name: Install R packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            tidyverse
            httr
            jsonlite
            gt
            gtExtras
            reactable
            dataui
            reactablefmtr
            ggtext
            glue
            scales
            paletteer
            ggrepel
            ggimage

      - name: Render
        run: quarto render

      - name: Publish to GitHub Pages
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}